version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: axelor-postgres
    environment:
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor
      POSTGRES_DB: axelor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U axelor"]
      interval: 10s
      timeout: 5s
      retries: 5

  axelor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: axelor-app
    environment:
      JAVA_OPTS: -Xms512m -Xmx1024m
      DB_URL: jdbc:postgresql://postgres:5432/axelor
      DB_USER: axelor
      DB_PASSWORD: axelor
    ports:
      - "7070:7070"
    depends_on:
      - postgres
    volumes:
      - ./data/uploads:/usr/local/tomcat/data/uploads
      - ./data/export:/usr/local/tomcat/data/export
      - ./data/indexes:/usr/local/tomcat/data/indexes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7070"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
